name: CI-Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.pull_request.labels.*.name), 'ci-skip')"
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: 'Install Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2
        with:
          install_components: 'beta,pubsub-emulator'
      - name: Prepare dot npmrc for private registry
        run: echo //npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }} >> ~/.npmrc
      - name: Bootstrap
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Lint
        run: npm run lint
        env:
          NODE_ENV: dev
          CI: true
      - name: 'Start Pub/Sub emulator'
        run: |
          gcloud beta emulators pubsub start --project=project-test --host-port=0.0.0.0:8085 &
      - name: Test
        run: npm run test
        env:
          NODE_ENV: test
          PUBSUB_EMULATOR_HOST: 'localhost:8085'
          CI: true
